---
# Standards: 1.2

- name: Create the GitLab machine
  gather_facts: False
  hosts:
    - gitlab
    - gitlab_runners
  roles:
    - virtual_machine

- name: Install GitLab
  hosts: gitlab
  become: true
  roles:
    - gitlab
  post_tasks:
    - name: Make sure GitLab backup is running on this machine
      cron:
        name: GitLab Backup
        minute: '15'
        hour: "{{ gitlab_backup_cron_hour }}"
        job: "/bin/gitlab-rake gitlab:backup:create SKIP={{ gitlab_backup_skip }} CRON=1"
    - name: Install python3
      yum:
        name: python3
        state: latest

- name: Install GitLab Runners on the above created machines
  hosts: gitlab_runners
  become: true
  pre_tasks:
    - name: Extract Runner Registration Token directly from GitLab Rails console
      become: true
      delegate_to: "{{ groups.gitlab_machine[0] }}"
      shell: '/usr/bin/gitlab-rails runner -e production "puts Gitlab::CurrentSettings.current_application_settings.runners_registration_token"'
      register: gitlab_runner_registration_token_result
      run_once: true
    - name: show gitlab_runner_registration_token_result
      set_fact:
        gitlab_runner_registration_token: "{{ gitlab_runner_registration_token_result.stdout }}"
  roles:
    - gitlab-runner